network:
  version: 2
  ethernets:
    enx00e04c680996:
      dhcp4: no 
  bridges:
    ihrbr0:
      interfaces: [enx00e04c680996]
      macaddress: 00:e0:4c:68:09:96
      dhcp4: yes
      dhcp6: yes
      dhcp4-overrides:
        route-metric: 20
      dhcp6-overrides:
        route-metric: 20

